import { useEffect, useState } from 'react';
import { Check, Database, ExternalLink, KeyRound, LockKeyhole, Satellite, ShieldCheck } from 'lucide-react';

interface Integration { id: string; name: string; purpose: string; status: string; documentation: string; fingerprint?: string; modelId?: string; }

export default function SettingsWorkspace() {
  const [preferencesLoaded, setPreferencesLoaded] = useState(false);
  const [temperature, setTemperature] = useState('celsius'); const [wind, setWind] = useState('kmh'); const [satellite, setSatellite] = useState('sentinel'); const [motion, setMotion] = useState(false);
  const [auth, setAuth] = useState<'loading'|'locked'|'open'>('loading'); const [integrations, setIntegrations] = useState<Integration[]>([]); const [password, setPassword] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { const saved = localStorage.getItem('farmlens-preferences'); if (saved) { try { const p = JSON.parse(saved); setTemperature(p.temperature ?? 'celsius'); setWind(p.wind ?? 'kmh'); setSatellite(p.satellite ?? 'sentinel'); setMotion(Boolean(p.motion)); } catch { localStorage.removeItem('farmlens-preferences'); } } setPreferencesLoaded(true); loadIntegrations(); }, []);
  useEffect(() => { if (!preferencesLoaded) return; localStorage.setItem('farmlens-preferences', JSON.stringify({ temperature, wind, satellite, motion })); document.documentElement.style.setProperty('scroll-behavior', motion ? 'auto' : 'smooth'); }, [temperature, wind, satellite, motion, preferencesLoaded]);
  const loadIntegrations = async () => { const response = await fetch('/api/settings/integrations'); if (response.ok) { const data = await response.json(); setIntegrations(data.integrations); setAuth('open'); } else setAuth('locked'); };
  const login = async (event: React.SyntheticEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(''); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error); return; } setPassword(''); await loadIntegrations(); };
  const testOlmo = async () => { setMessage('Testing secure server connection…'); const response = await fetch('/api/settings/integrations/olmoearth/test', { method: 'POST' }); const data = await response.json(); setMessage(response.ok ? `Connection succeeded at ${new Date(data.testedAt).toLocaleTimeString('en-GH')}.` : data.error); };
  const testEarthEngine = async () => { setMessage('Testing Earth Engine project and server authentication…'); try { const response = await fetch('/api/settings/earth-engine/test', { method: 'POST' }); const data = await response.json(); setMessage(response.ok ? 'Earth Engine connection verified.' : data.error); } catch { setMessage('Connection test unavailable.'); } };
  return <div className="settings-layout">
    <section className="panel panel-pad settings-section"><div className="settings-title"><span><Check/></span><div><h2>Preferences</h2><p>Stored only in this browser.</p></div></div>
      <div className="settings-form"><SettingSelect label="Temperature units" value={temperature} onChange={setTemperature} options={[['celsius','Celsius (°C)'],['fahrenheit','Fahrenheit (°F)']]}/><SettingSelect label="Wind units" value={wind} onChange={setWind} options={[['kmh','Kilometres per hour'],['ms','Metres per second']]}/><SettingSelect label="Preferred satellite provider" value={satellite} onChange={setSatellite} options={[['sentinel','Sentinel Hub'],['agro','AgroMonitoring'],['nasa','NASA AppEEARS']]}/><SettingSelect label="Language" value="english" onChange={() => {}} options={[['english','English'],['future','More Ghanaian languages coming']]}/><label className="toggle-row"><span><b>Reduce motion</b><small>Limit map and interface animation.</small></span><input type="checkbox" checked={motion} onChange={(e) => setMotion(e.target.checked)}/></label></div>
    </section>
    <section className="panel panel-pad settings-section" id="integrations"><div className="settings-title"><span><ShieldCheck/></span><div><h2>Integrations</h2><p>Administrator-only provider credentials.</p></div></div>
      {auth === 'loading' && <div className="skeleton sk-row"/>}
      {auth === 'locked' && <div className="admin-lock"><LockKeyhole/><div><h3>Administrator access</h3><p>Sign in to read provider status or test credentials. Secret values are never returned to this browser.</p><form onSubmit={login}><input className="input" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Administrator password" autoComplete="current-password"/><button className="btn btn-primary" type="submit">Unlock integrations</button></form>{message && <p className="form-message">{message}</p>}<small>Not configured? Set a scrypt-formatted ADMIN_PASSWORD_HASH and an APP_ENCRYPTION_KEY of at least 32 characters.</small></div></div>}
      {auth === 'open' && <><div className="integration-grid">{integrations.map((item) => <article className="integration-card" id={item.id === 'olmoEarth' ? 'olmoearth' : undefined} key={item.id}><div className="integration-head"><span>{item.id === 'olmoEarth' ? <Database/> : <Satellite/>}</span><div><h3>{item.name}</h3><p>{item.purpose}</p></div><em data-status={item.status}>{item.status.replace('_',' ')}</em></div><div className="credential-row"><KeyRound/><span>{item.fingerprint ?? 'No credential configured'}{item.modelId ? ` · model ${item.modelId}` : ''}</span></div><div className="integration-actions">{item.id === 'olmoEarth' && <button className="btn" onClick={testOlmo} disabled={item.status !== 'connected'}>Test connection</button>}<a className="btn btn-ghost" href={item.documentation} target="_blank" rel="noreferrer">Docs <ExternalLink/></a></div></article>)}</div>{message && <p className="form-message">{message}</p>}<div className="secure-note"><ShieldCheck/><p><b>Environment-managed secrets</b><br/>This deployment never writes credentials to its filesystem. Add, replace or revoke provider keys in the deployment secret store, then restart the service. Only masked fingerprints are shown here.</p></div></>}
    </section>
    {auth === 'open' && <section className="panel panel-pad"><h2>Earth Engine setup</h2><p>Project: mapssp-1499716002898. Railway authenticates with a least-privilege service-account JSON stored as a Railway secret; local development can use Application Default Credentials. Visitors never sign into Google and never receive the credential.</p><button className="btn" onClick={testEarthEngine}>Test Earth Engine connection</button><p className="meta">Set GEE_SERVICE_ACCOUNT_JSON in Railway Variables, then redeploy and run this test. Never paste a Gmail password or private key into this page. Visitor requests use the server project's quota: small areas only, no batch exports or model training.</p></section>}
  </div>;
}

function SettingSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (v:string)=>void; options: string[][] }) { return <label><span className="label">{label}</span><select className="input" value={value} onChange={(e)=>onChange(e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>; }
